import Head from "next/head";
import {
  ViewGridIcon,
  MicrophoneIcon,
  SearchIcon,
  XIcon,
  UserIcon,
} from "@heroicons/react/solid";
import Image from "next/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);


  const clear = (e) => {
    const inputValue = e.target.value;
    document.getElementById("clearButton").style.display = "block";

    if (inputValue.length == 0) {
      document.getElementById("clearButton").style.display = "";
    }
  };

  const search = (e) => {
    e.preventDefault();


    const term = searchInputRef.current.value;

    if (!term) return;
    router.push(`/All?term=${term}`);
  };
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700 ">
        {/* Left header*/}
        <div className="flex space-x-4 items-center">
          <p
            onClick={() =>
              (location.href =
                "https://about.google/?utm_source=google-IN&utm_medium=referral&utm_campaign=hp-footer&fg=1")
            }
            className="link"
          >
            About
          </p>
          <p
            onClick={() => (location.href = "https://store.google.com/")}
            className="link"
          >
            Store
          </p>
        </div>

        {/* Right header*/}
        <div className="flex space-x-4 items-center">
          <p
            onClick={() => (location.href = "https://mail.google.com/mail/")}
            className="link"
          >
            Gmail
          </p>
          <p
            onClick={() =>
              router.push(
                `/ImageSearch?term=${
                  router.query.term ? router.query.term : ""
                }`
              )
            }
            className="link"
          >
            Images
          </p>

          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          {/* Avatar */}
          <UserIcon className="h-8 p-1.5 bg-gray-200 rounded-full" />
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center mt-20 flex-grow w-4/5">
        {/* Image */}
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          width={300}
          height={100}
          priority
        />

        {/* Search Section */}
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
            onChange={clear}
          />
          <XIcon
            id="clearButton"
            className="h-5 w-7 mr-2 border-r-2 border-gray-200 px-1 cursor-pointer text-gray-500 sm:mr-3 hidden"
            onClick={() => {
              searchInputRef.current.value = "";
              document.getElementById("clearButton").style.display = "none";
              searchInputRef.current.focus();
            }}
          />
          <MicrophoneIcon className="h-5 text-gray-500" />
        </div>

        {/* Buttons */}
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:gap-x-4">
          <button onClick={search} className="btn">
            Google Search
          </button>
            <span className="btn cursor-pointer text-center" onClick={() => location.href="https://www.google.com/doodles"}>
              I'm Feeling Lucky
            </span>
        </div>
      </form>

      <Footer />
    </div>
  );
}
